name: Build Eleventy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies & build
              run: |
                  npm ci
                  npm run build

            - run: mkdir -p _site/css/

            - name: Compile custom.css from custom.scss
              uses: gha-utilities/sass-build@v0.3.0
              with:
                  source: scss/custom.scss
                  destination: _site/css/custom.css

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  publish_dir: ./_site
                  github_token: ${{ secrets.GITHUB_TOKEN }}
